# 프로젝트 Root 폴더
version: '3.2'

services: 
  frontend:
    image: frontend-vue
    build:
      context: front-end/
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
      - "443:443" 
    # [인증서 파일 저장 경로]:/var/www/html
    volumes:
      - /home/ubuntu/docker-volume/ssl_folder:/var/www/html
    container_name: "frontend"
  
  backend:
    image: backend-spring
    build:
      context: back-end/
      dockerfile: Dockerfile
    ports:
      - "8443:8443"  
    volumes:
      - /home/ubuntu/docker-volume/ssl_folder:/root
    container_name: "backend"